import {IOut} from '@graphqldb/types';
import {IProcessor} from '../types';
import {removeEmptyLines} from '../utils/removeEmptyLines';

export const importsProcessor = ({options, prev}: IProcessor): IOut => {
  return {
    ...prev,
    ts: removeEmptyLines(`// THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
${prev.ts || ''}
import * as fs from 'fs';
import * as path from 'path';
import adapter from '${options?.adapter || '@graphqldb/adapter-memory'}';
import { setAdapter, getAdapter, validate${
      options.generateApi
        ? ', getArguments, getContext, checkPermissions, wrapResolver'
        : ''
    } } from '@graphqldb/client';
setAdapter(adapter);`),
  };
};
